### ISSUE TITLE
BUG - if stdout is nil to yaml-printer, there will be a fault for yamlFile[len(yamlFile)-1]

### ISSUE THREAD

**Issue by ada-wang** [ada-wang/yaml-printer#2]
```
$ cat configtx.yaml | yaml-printer 
cat: configtx.yaml: No such file or directory
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffff pc=0x4f2cbc]

goroutine 1 [running]:
runtime.throw(0x530bee, 0x5)
	/opt/go/src/runtime/panic.go:608 +0x72 fp=0xc000077dc0 sp=0xc000077d90 pc=0x428782
runtime.sigpanic()
	/opt/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc000077e10 sp=0xc000077dc0 pc=0x43b6a5
main.main()
	/home/wang/GO_WORKSPACE/src/github.com/ada-wang/yaml-printer/main.go:27 +0x20c fp=0xc000077f98 sp=0xc000077e10 pc=0x4f2cbc
runtime.main()
	/opt/go/src/runtime/proc.go:201 +0x207 fp=0xc000077fe0 sp=0xc000077f98 pc=0x42a0f7
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x4520f1

```

**Comment by ada-wang** [comment]
FIXED
